name: Update MD-Repo-CLI Release Table
on:
  release:
    types: [published]

jobs:
  handle-published-release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the version of Python to use
  
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install requests
  
    - name: Run Python script
      run: |
        python .github/workflows/update_release_table.py
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
